# Generated by Django 4.1.3 on 2022-12-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('filler_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('filler_name', models.CharField(max_length=100)),
                ('filler_v', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='filler',
            constraint=models.CheckConstraint(check=models.Q(('filler_id__length', 6), ('filler_id__regex', '[A-Z][A-Z][0-9][0-9][0-9][0-9]')), name='filler_id_constraint'),
        ),
        migrations.AddConstraint(
            model_name='filler',
            constraint=models.CheckConstraint(check=models.Q(('filler_name__length__gt', 0)), name='filler_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='filler',
            constraint=models.CheckConstraint(check=models.Q(('filler_v__gte', 0)), name='filler_v_constraint'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(check=models.Q(('equipment_id__length', 6), ('equipment_id__regex', '[A-Z][A-Z][0-9][0-9][0-9][0-9]')), name='equipment_id_constraint'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(check=models.Q(('number__gte', 0)), name='equipment_number_constraint'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gt', 0)), name='equipment_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='equipment_price_constraint'),
        ),
    ]
