# Generated by Django 4.1.3 on 2023-02-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basehousewithoutwateranalysis',
            options={'verbose_name': 'Коттедж, нет анализа', 'verbose_name_plural': 'Коттедж, нет анализа'},
        ),
        migrations.AlterModelOptions(
            name='basehousewithwateranalysis',
            options={'verbose_name': 'Коттедж, есть анализ', 'verbose_name_plural': 'Коттедж, есть анализ'},
        ),
        migrations.AlterModelOptions(
            name='countryhousewithoutwateranalysis',
            options={'verbose_name': 'Дача, нет анализа', 'verbose_name_plural': 'Дача, нет анализа'},
        ),
        migrations.AlterModelOptions(
            name='countryhousewithwateranalysis',
            options={'verbose_name': 'Дача, есть анализ'},
        ),
        migrations.AlterModelOptions(
            name='flathousewithoutwateranalysis',
            options={'verbose_name': 'Квартира, нет анализа', 'verbose_name_plural': 'Квартира, нет анализа'},
        ),
        migrations.AlterModelOptions(
            name='flathousewithwateranalysis',
            options={'verbose_name': 'Квартира, есть анализ', 'verbose_name_plural': 'Квартира, есть анализ'},
        ),
        migrations.AlterUniqueTogether(
            name='flathousewithoutwateranalysis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flathousewithoutwateranalysis',
            name='water_hardness',
            field=models.BooleanField(default=False, verbose_name='жесткость'),
        ),
        migrations.AlterField(
            model_name='basehousewithoutwateranalysis',
            name='water_ferum',
            field=models.BooleanField(verbose_name='железо'),
        ),
        migrations.AlterField(
            model_name='basehousewithoutwateranalysis',
            name='water_hardness',
            field=models.BooleanField(verbose_name='жесткость'),
        ),
        migrations.AlterField(
            model_name='basehousewithoutwateranalysis',
            name='water_smell',
            field=models.BooleanField(verbose_name='запах'),
        ),
        migrations.AlterField(
            model_name='basehousewithoutwateranalysis',
            name='water_v_used_per_hour',
            field=models.FloatField(choices=[(1.0, '1 - 2 человека (до 1,3 куб.м./ч)'), (1.3, ' 3 - 4 человека (до 2-х куб.м./ч)'), (2.0, '5 - 8 человек (до 2,5-х куб.м./ч)'), (2.5, '8 и более человек(от 2,5 - х куб.м./ч)')], verbose_name='людей в доме'),
        ),
        migrations.AlterField(
            model_name='basehousewithwateranalysis',
            name='water_ferum',
            field=models.FloatField(choices=[(0, 'до 0,3'), (0.3, 'до 0,9'), (0.9, 'до 8'), (8, 'от 8')], verbose_name='железо'),
        ),
        migrations.AlterField(
            model_name='basehousewithwateranalysis',
            name='water_hardness',
            field=models.IntegerField(choices=[(0, 'до 3'), (3, 'до 8'), (8, 'до 15'), (20, 'от 15')], verbose_name='жесткость'),
        ),
        migrations.AlterField(
            model_name='basehousewithwateranalysis',
            name='water_mpc',
            field=models.BooleanField(verbose_name='другие примеси'),
        ),
        migrations.AlterField(
            model_name='basehousewithwateranalysis',
            name='water_smell',
            field=models.BooleanField(verbose_name='запах'),
        ),
        migrations.AlterField(
            model_name='basehousewithwateranalysis',
            name='water_v_used_per_hour',
            field=models.FloatField(choices=[(1.0, '1 - 2 человека (до 1,3 куб.м./ч)'), (1.3, ' 3 - 4 человека (до 2-х куб.м./ч)'), (2.0, '5 - 8 человек (до 2,5-х куб.м./ч)'), (2.5, '8 и более человек(от 2,5 - х куб.м./ч)')], verbose_name='людей в доме'),
        ),
        migrations.AlterField(
            model_name='countryhousewithoutwateranalysis',
            name='water_ferum',
            field=models.BooleanField(verbose_name='железо'),
        ),
        migrations.AlterField(
            model_name='countryhousewithoutwateranalysis',
            name='water_hardness',
            field=models.BooleanField(verbose_name='жесткость'),
        ),
        migrations.AlterField(
            model_name='countryhousewithoutwateranalysis',
            name='water_smell',
            field=models.BooleanField(verbose_name='запах'),
        ),
        migrations.AlterField(
            model_name='countryhousewithoutwateranalysis',
            name='water_v_used_per_hour',
            field=models.FloatField(choices=[(1.0, '1 - 2 человека (до 1,3 куб.м./ч)'), (1.3, ' 3 - 4 человека (до 2-х куб.м./ч)')], verbose_name='лидей в доме'),
        ),
        migrations.AlterField(
            model_name='countryhousewithwateranalysis',
            name='water_ferum',
            field=models.FloatField(choices=[(0, 'до 0,3'), (0.3, 'до 0,9'), (0.9, 'от 0,9')], verbose_name='железо'),
        ),
        migrations.AlterField(
            model_name='countryhousewithwateranalysis',
            name='water_hardness',
            field=models.IntegerField(choices=[(0, 'до 3'), (3, 'до 7'), (7, 'от 7')], verbose_name='жесткость'),
        ),
        migrations.AlterField(
            model_name='countryhousewithwateranalysis',
            name='water_mpc',
            field=models.BooleanField(verbose_name='другие примеси'),
        ),
        migrations.AlterField(
            model_name='countryhousewithwateranalysis',
            name='water_smell',
            field=models.BooleanField(verbose_name='запах'),
        ),
        migrations.AlterField(
            model_name='countryhousewithwateranalysis',
            name='water_v_used_per_hour',
            field=models.FloatField(choices=[(1.0, '1 - 2 человека (до 1,3 куб.м./ч)'), (1.3, ' 3 - 4 человека (до 2-х куб.м./ч)')], verbose_name='людей в доме'),
        ),
        migrations.AlterField(
            model_name='flathousewithoutwateranalysis',
            name='water_ferum',
            field=models.BooleanField(verbose_name='железо'),
        ),
        migrations.AlterUniqueTogether(
            name='flathousewithoutwateranalysis',
            unique_together={('water_hardness', 'water_ferum')},
        ),
        migrations.RemoveField(
            model_name='flathousewithoutwateranalysis',
            name='water_harness',
        ),
    ]
