# Generated by Django 4.1.3 on 2023-05-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplectMontage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.complects')),
                ('montage_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.montagework')),
            ],
        ),
        migrations.AddField(
            model_name='montagework',
            name='complects',
            field=models.ManyToManyField(through='calc_app.ComplectMontage', to='calc_app.complects'),
        ),
    ]
