# Generated by Django 4.1.3 on 2023-06-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0002_complectmontage_montagework_complects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('exceeding_consecuences', models.TextField(verbose_name='последствия превышения')),
                ('recommendations', models.TextField(verbose_name='рекомендации')),
                ('criitical_value', models.FloatField(verbose_name='критическое значение')),
            ],
        ),
        migrations.AlterField(
            model_name='contractequipment',
            name='number',
            field=models.IntegerField(choices=[(1, 'до 2.0'), (2, 'до 3.0'), (3, 'до 4.0')]),
        ),
        migrations.AlterField(
            model_name='fullwaterparametrs',
            name='ammonium',
            field=models.FloatField(choices=[(0, 'до 1.0'), (1, 'до 2.0'), (2, 'до 3.0'), (3, 'до 4.0'), (4, 'до 5.0'), (5, 'до 6.0')], verbose_name='аммоний'),
        ),
        migrations.AlterField(
            model_name='fullwaterparametrs',
            name='ferum',
            field=models.FloatField(choices=[(0, 'до 1.0'), (1, 'до 2.0'), (2, 'до 3.0'), (3, 'до 4.0'), (4, 'до 5.0'), (5, 'до 6.0'), (6, 'до 7.0'), (7, 'до 8.0'), (8, 'до 9.0'), (9, 'до 10.0'), (10, 'до 11.0'), (11, 'до 12.0'), (12, 'до 13.0'), (13, 'до 14.0'), (14, 'до 15.0'), (15, 'до 16.0'), (16, 'до 17.0'), (17, 'до 18.0'), (18, 'до 19.0'), (19, 'до 20.0'), (20, 'до 21.0')], verbose_name='железо'),
        ),
        migrations.AlterField(
            model_name='fullwaterparametrs',
            name='hardness',
            field=models.FloatField(choices=[(0, 'до 1.0'), (1, 'до 2.0'), (2, 'до 3.0'), (3, 'до 4.0'), (4, 'до 5.0'), (5, 'до 6.0'), (6, 'до 7.0'), (7, 'до 8.0'), (8, 'до 9.0'), (9, 'до 10.0'), (10, 'до 11.0'), (11, 'до 12.0'), (12, 'до 13.0'), (13, 'до 14.0'), (14, 'до 15.0'), (15, 'до 16.0')], verbose_name='жесткость'),
        ),
        migrations.AlterField(
            model_name='fullwaterparametrs',
            name='hydrogen_sulfite',
            field=models.FloatField(choices=[(0, 'до 1.0'), (1, 'до 2.0'), (2, 'до 3.0'), (3, 'до 4.0'), (4, 'до 5.0'), (5, 'до 6.0')], verbose_name='сервоводород'),
        ),
        migrations.AlterField(
            model_name='fullwaterparametrs',
            name='manganese',
            field=models.FloatField(choices=[(0, 'до 1.0'), (1, 'до 2.0'), (2, 'до 3.0'), (3, 'до 4.0'), (4, 'до 5.0'), (5, 'до 6.0')], verbose_name='марганец'),
        ),
        migrations.AlterField(
            model_name='fullwaterparametrs',
            name='po',
            field=models.FloatField(choices=[(0, 'до 1.0'), (1, 'до 2.0'), (2, 'до 3.0'), (3, 'до 4.0'), (4, 'до 5.0'), (5, 'до 6.0'), (6, 'до 7.0'), (7, 'до 8.0'), (8, 'до 9.0'), (9, 'до 10.0'), (10, 'до 11.0'), (11, 'до 12.0'), (12, 'до 13.0'), (13, 'до 14.0'), (14, 'до 15.0'), (15, 'до 16.0')], verbose_name='ПО'),
        ),
    ]
