# Generated by Django 4.1.3 on 2023-02-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0002_alter_basehousewithoutwateranalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basehouseanalysisequimpent',
            options={'verbose_name': 'Коттедж --  борудование (есть анализ)', 'verbose_name_plural': 'Коттедж --  борудование (есть анализ)'},
        ),
        migrations.AlterModelOptions(
            name='basehousenoanalysisequipment',
            options={'verbose_name': 'Коттедж --  борудование (нет анализа)', 'verbose_name_plural': 'Коттедж --  борудование (нет анализа)'},
        ),
        migrations.AlterModelOptions(
            name='countryhousenoanalysisequipment',
            options={'verbose_name': 'Дача --  борудование (нет анализа)', 'verbose_name_plural': 'Дача --  борудование (нет анализа)'},
        ),
        migrations.AlterModelOptions(
            name='coutryhouseanalysisequipment',
            options={'verbose_name': 'Дача --  борудование (есть анализ)', 'verbose_name_plural': 'Дача --  борудование (есть анализ)'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Тип оборудования', 'verbose_name_plural': 'Типы оборудования'},
        ),
        migrations.AlterModelOptions(
            name='flathouseanalysisequipment',
            options={'verbose_name': 'Квартира --  борудование (есть анализ)', 'verbose_name_plural': 'Квартира --  борудование (есть анализ)'},
        ),
        migrations.AlterModelOptions(
            name='flathousenoanalysisequipment',
            options={'verbose_name': 'Капртира --  борудование (нет анализа)', 'verbose_name_plural': 'Капртира --  борудование (нет анализа)'},
        ),
        migrations.AddField(
            model_name='basehousewithoutwateranalysis',
            name='equipments',
            field=models.ManyToManyField(through='calc_app.BaseHouseNoAnalysisEquipment', to='calc_app.equipment'),
        ),
        migrations.AddField(
            model_name='basehousewithwateranalysis',
            name='equipments',
            field=models.ManyToManyField(through='calc_app.BaseHouseAnalysisEquimpent', to='calc_app.equipment'),
        ),
        migrations.AddField(
            model_name='countryhousewithoutwateranalysis',
            name='equipments',
            field=models.ManyToManyField(through='calc_app.CountryHouseNoAnalysisEquipment', to='calc_app.equipment'),
        ),
        migrations.AddField(
            model_name='countryhousewithwateranalysis',
            name='equipments',
            field=models.ManyToManyField(through='calc_app.CoutryHouseAnalysisEquipment', to='calc_app.equipment'),
        ),
        migrations.AddField(
            model_name='flathousewithoutwateranalysis',
            name='equipments',
            field=models.ManyToManyField(through='calc_app.FlatHouseNoAnalysisEquipment', to='calc_app.equipment'),
        ),
        migrations.AddField(
            model_name='flathousewithwateranalysis',
            name='equipments',
            field=models.ManyToManyField(through='calc_app.FlatHouseAnalysisEquipment', to='calc_app.equipment'),
        ),
        migrations.AlterField(
            model_name='basehouseanalysisequimpent',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='basehouseanalysisequimpent',
            name='input_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.basehousewithwateranalysis', verbose_name='входные данные'),
        ),
        migrations.AlterField(
            model_name='basehousenoanalysisequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='basehousenoanalysisequipment',
            name='input_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.basehousewithoutwateranalysis', verbose_name='входные данные'),
        ),
        migrations.AlterField(
            model_name='countryhousenoanalysisequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='countryhousenoanalysisequipment',
            name='input_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.countryhousewithoutwateranalysis', verbose_name='входные данные'),
        ),
        migrations.AlterField(
            model_name='coutryhouseanalysisequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='coutryhouseanalysisequipment',
            name='input_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.countryhousewithwateranalysis', verbose_name='входные данные'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(max_length=40, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_price',
            field=models.FloatField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='type_discount',
            field=models.FloatField(verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='type_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='тип оборудования'),
        ),
        migrations.AlterField(
            model_name='flathouseanalysisequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='flathouseanalysisequipment',
            name='input_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.flathousewithwateranalysis', verbose_name='входные данные'),
        ),
        migrations.AlterField(
            model_name='flathousenoanalysisequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='flathousenoanalysisequipment',
            name='inout_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.flathousewithoutwateranalysis', verbose_name='входные данные'),
        ),
        migrations.AlterField(
            model_name='flathousewithwateranalysis',
            name='water_ferum',
            field=models.FloatField(choices=[(0, 'до 0,6'), (0.6, 'до 0,9'), (0.9, 'от 0,9')], verbose_name='железо'),
        ),
        migrations.AlterField(
            model_name='flathousewithwateranalysis',
            name='water_hardness',
            field=models.IntegerField(choices=[(0, 'до 3'), (3, 'до 7'), (7, 'от 7')], verbose_name='жесткость'),
        ),
    ]
