# Generated by Django 4.1.3 on 2023-06-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0004_remove_fullwaterparametrs_exceeding_consequence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admixture',
            options={'verbose_name': 'Примесь', 'verbose_name_plural': 'Примеси'},
        ),
        migrations.RemoveField(
            model_name='builderobject',
            name='human_daily_norm',
        ),
        migrations.RemoveField(
            model_name='builderobject',
            name='people_number',
        ),
        migrations.RemoveField(
            model_name='builderobject',
            name='water_consumption',
        ),
    ]
